const data =  {
    products : [
        {
            _id: 1,
            name: 'Arduino Uno',
            category: 'Motherboards',
            image: 'images/product-1.jpg',
            price: 132,
            brand: 'Arduino',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: 2,
            name: 'Arduino Uno 1',
            category: 'Motherboards',
            image: 'images/product-1.jpg',
            price: 132,
            brand: 'Arduino',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: 3,
            name: 'Arduino Uno',
            category: 'Motherboards',
            image: 'images/product-1.jpg',
            price: 132,
            brand: 'Arduino',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: 4,
            name: 'Arduino Uno',
            category: 'Motherboards',
            image: 'images/product-1.jpg',
            price: 132,
            brand: 'Arduino',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: 4,
            name: 'Arduino Uno',
            category: 'Motherboards',
            image: 'images/product-1.jpg',
            price: 132,
            brand: 'Arduino',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: 4,
            name: 'Arduino Uno',
            category: 'Motherboards',
            image: 'images/product-1.jpg',
            price: 132,
            brand: 'Arduino',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: 4,
            name: 'Arduino Uno',
            category: 'Motherboards',
            image: 'images/product-1.jpg',
            price: 132,
            brand: 'Arduino',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: 4,
            name: 'Arduino Uno',
            category: 'Motherboards',
            image: 'images/product-1.jpg',
            price: 132,
            brand: 'Arduino',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        }
    ]
}

export default data;